[ { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333792147255300,
    id_str: '557333792147255296',
    text: '"@5HFHelp: Quote if u love Camila Cabello and want @sinucabello follows! #PreorderReflectionOniTunes &lt;3" ❤❤',
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 713122557,
       id_str: '713122557',
       name: 'TYSM DINAH ',
       screen_name: 'fifthdll',
       location: 'I love you @himitchie ',
       profile_location: null,
       description: 'Demi Lovato,Justin Bieber and Fifth harmony saved my life...JUSTIN,AUSTIN,NASH,WESLEY AND IGOR FOLLOWS 2/6',
       url: 'https://t.co/443BAtPqP4',
       entities: [Object],
       protected: false,
       followers_count: 5627,
       friends_count: 5344,
       listed_count: 8,
       created_at: 'Sun Oct 13 18:46:28 +0000 2013',
       favourites_count: 5076,
       utc_offset: -7200,
       time_zone: 'Mid-Atlantic',
       geo_enabled: false,
       verified: false,
       statuses_count: 82816,
       lang: 'pt',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'ACDED6',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/536147160106954753/RGb2g2Mj.png',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/536147160106954753/RGb2g2Mj.png',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/556504998473777152/3EGPaTfD_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/556504998473777152/3EGPaTfD_normal.png',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/713122557/1421447409',
       profile_link_color: '090A0A',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: 'EFEFEF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [Object],
       urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333792084353000,
    id_str: '557333792084353024',
    text: '@JungMin0403 how is your back pain baby i hope you are feeling better now 😟😟😟 I\'ll pray allah to keep you safe my love 💖💖💖💖',
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 167325741,
    in_reply_to_user_id_str: '167325741',
    in_reply_to_screen_name: 'JungMin0403',
    user: 
     { id: 2181087778,
       id_str: '2181087778',
       name: '❤Park Sona Min❤',
       screen_name: 'park_sona',
       location: '❤TripleS❤Forever',
       profile_location: null,
       description: 'Jung Min Followed me For 8 hours  ❤❤❤ my lucky day❤❤❤30/10/2014❤❤❤                                                                          S❤S❤5❤0❤1',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 1393,
       friends_count: 52,
       listed_count: 6,
       created_at: 'Thu Nov 14 19:35:47 +0000 2013',
       favourites_count: 21871,
       utc_offset: 7200,
       time_zone: 'Kyiv',
       geo_enabled: true,
       verified: false,
       statuses_count: 28824,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/551723820927578112/u3mdFSnc_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/551723820927578112/u3mdFSnc_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2181087778/1420395921',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333792030199800,
    id_str: '557333792030199808',
    text: 'RT @94HAPPILYHARRY: @Harry_Styles\n\nhiii  ℋ!\nyou deserve all the love \nand happiness in the world \nplease follow me babe\ni love you so much …',
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 2907227493,
       id_str: '2907227493',
       name: '♥8-27-15♥',
       screen_name: 'WannaBeThinpso',
       location: 'Stuck in Limbo',
       profile_location: null,
       description: 'He wore an itsy bitsy teeny queeny grey super soft beanie Xx',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 271,
       friends_count: 221,
       listed_count: 1,
       created_at: 'Sat Dec 06 04:01:58 +0000 2014',
       favourites_count: 2040,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4458,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/541801741264510976/pB2Q-u0c.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/541801741264510976/pB2Q-u0c.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/556919143954673669/uL3RwE4z_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/556919143954673669/uL3RwE4z_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2907227493/1421614844',
       profile_link_color: 'F5ABB5',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: 
     { metadata: [Object],
       created_at: 'Tue Jan 20 00:09:08 +0000 2015',
       id: 557328937907654660,
       id_str: '557328937907654658',
       text: '@Harry_Styles\n\nhiii  ℋ!\nyou deserve all the love \nand happiness in the world \nplease follow me babe\ni love you so much \n💓🌿👼\n39,294',
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: 181561712,
       in_reply_to_user_id_str: '181561712',
       in_reply_to_screen_name: 'Harry_Styles',
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweet_count: 2,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       lang: 'en' },
    retweet_count: 2,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333792021807100,
    id_str: '557333792021807105',
    text: 'RT @justinbieber: i love u. my #Beliebers http://t.co/3oMFQZWkDP',
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 1151238672,
       id_str: '1151238672',
       name: 'Isabella',
       screen_name: '_itssdrew',
       location: 'Brasilia',
       profile_location: null,
       description: 'cara, do fundo do meu coração, vai tomar no seu cu',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 593,
       friends_count: 625,
       listed_count: 0,
       created_at: 'Tue Feb 05 15:40:32 +0000 2013',
       favourites_count: 2458,
       utc_offset: -7200,
       time_zone: 'Brasilia',
       geo_enabled: false,
       verified: false,
       statuses_count: 17215,
       lang: 'pt',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'FFFFFF',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/459772235083821056/FitFpx35.png',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/459772235083821056/FitFpx35.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/556993408330248192/HHkdv10X_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/556993408330248192/HHkdv10X_normal.png',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/1151238672/1421632598',
       profile_link_color: '000000',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: 
     { metadata: [Object],
       created_at: 'Mon Jul 01 21:50:40 +0000 2013',
       id: 351820174854332400,
       id_str: '351820174854332416',
       text: 'i love u. my #Beliebers http://t.co/3oMFQZWkDP',
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweet_count: 230532,
       favorite_count: 183502,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    retweet_count: 230532,
    favorite_count: 0,
    entities: 
     { hashtags: [Object],
       symbols: [],
       user_mentions: [Object],
       urls: [],
       media: [Object] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791979479040,
    id_str: '557333791979479041',
    text: 'Wishing the happiest of birthdays to one of the best people in this world😍💘💘💘💘💘 Hope you\'re doing well my love! @jweatherless',
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 410219412,
       id_str: '410219412',
       name: 'Victoria Galaviz',
       screen_name: 'VictoriaGalaviz',
       location: '',
       profile_location: null,
       description: 'Rejoice in the Lord.. Always. \nPsalms 46:5 // AZ // IG: victoriagalaviz',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 329,
       friends_count: 402,
       listed_count: 0,
       created_at: 'Fri Nov 11 20:15:21 +0000 2011',
       favourites_count: 1836,
       utc_offset: -28800,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 7558,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'DBE9ED',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/363586666/light-bulb.jpg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/363586666/light-bulb.jpg',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/557255624510013440/knsZNgNY_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/557255624510013440/knsZNgNY_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/410219412/1419392815',
       profile_link_color: '050105',
       profile_sidebar_border_color: 'DBE9ED',
       profile_sidebar_fill_color: 'EDEAED',
       profile_text_color: '000000',
       profile_use_background_image: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791937925100,
    id_str: '557333791937925122',
    text: '@megan_lats23 @tlawww look I love the kid ight👌',
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    truncated: false,
    in_reply_to_status_id: 557333140516384800,
    in_reply_to_status_id_str: '557333140516384771',
    in_reply_to_user_id: 2180991949,
    in_reply_to_user_id_str: '2180991949',
    in_reply_to_screen_name: 'megan_lats23',
    user: 
     { id: 2168777916,
       id_str: '2168777916',
       name: 'Nolan Woodell⚾️⚽️',
       screen_name: 'nwoodell13',
       location: '',
       profile_location: null,
       description: 'Je espère en Dieu || IG: nwoodell13',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 275,
       friends_count: 193,
       listed_count: 0,
       created_at: 'Fri Nov 01 17:10:52 +0000 2013',
       favourites_count: 1689,
       utc_offset: -18000,
       time_zone: 'Eastern Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 2477,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/555867696827752448/lMVb5wNb_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/555867696827752448/lMVb5wNb_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2168777916/1421423371',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791589802000,
    id_str: '557333791589801985',
    text: 'I love the @VacavillePolice Department.  They always come through!',
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 133188034,
       id_str: '133188034',
       name: 'Laura Cole',
       screen_name: 'ColeProMedia',
       location: 'Northern California ',
       profile_location: null,
       description: 'President/Owner of Cole Pro Media. Helping others report the real story. I don\'t have dreams I have GOALS!',
       url: 'http://t.co/vIB7bTT7aU',
       entities: [Object],
       protected: false,
       followers_count: 1713,
       friends_count: 638,
       listed_count: 63,
       created_at: 'Thu Apr 15 06:50:19 +0000 2010',
       favourites_count: 0,
       utc_offset: -25200,
       time_zone: 'Arizona',
       geo_enabled: false,
       verified: false,
       statuses_count: 8123,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '009AB9',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/446407265583521793/uVtIY46x.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/446407265583521793/uVtIY46x.jpeg',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/555545891705065472/Xc-kUWa-_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/555545891705065472/Xc-kUWa-_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/133188034/1395192702',
       profile_link_color: '009AB9',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: '95E8EC',
       profile_text_color: '3C3940',
       profile_use_background_image: false,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791514329100,
    id_str: '557333791514329088',
    text: '@cabduluk Our app is made for kindness :) we\'d love you to check it out (&amp; vote if you like it)! http://t.co/BHPjtHfV67',
    source: '<a href="https://zapier.com/" rel="nofollow">Zapier.com</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1314311472,
    in_reply_to_user_id_str: '1314311472',
    in_reply_to_screen_name: 'cabduluk',
    user: 
     { id: 2618352547,
       id_str: '2618352547',
       name: 'Outpour',
       screen_name: 'OutpourApp',
       location: 'San Francisco, CA',
       profile_location: null,
       description: 'http://t.co/1MtQKDDdc9 Go find the beauty in people and tell them. Because people should know they are loved :)',
       url: 'http://t.co/4v8Y0j50Ad',
       entities: [Object],
       protected: false,
       followers_count: 474,
       friends_count: 171,
       listed_count: 6,
       created_at: 'Fri Jul 11 20:00:04 +0000 2014',
       favourites_count: 995,
       utc_offset: -28800,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 10721,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/537696507999166464/bx4_gDgl_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/537696507999166464/bx4_gDgl_normal.png',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2618352547/1417032045',
       profile_link_color: '00ACA9',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: 
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791455191040,
    id_str: '557333791455191040',
    text: 'Hi harry! @Harry_Styles \nI hope your day is going great◡̈\nDo you mind sparing me a follow?\nIt\'d make me so happy.\nI love you so much! x 2253',
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 2441197010,
       id_str: '2441197010',
       name: 'ella !¡ // 172',
       screen_name: 'shakyhes',
       location: '',
       profile_location: null,
       description: '“he made my dull heart light up with joy”',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 3100,
       friends_count: 599,
       listed_count: 47,
       created_at: 'Sun Apr 13 07:05:57 +0000 2014',
       favourites_count: 31275,
       utc_offset: -25200,
       time_zone: 'Arizona',
       geo_enabled: true,
       verified: false,
       statuses_count: 39167,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/550623797082988546/-WeCQE3j_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/550623797082988546/-WeCQE3j_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2441197010/1419585231',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { metadata: { iso_language_code: 'en', result_type: 'recent' },
    created_at: 'Tue Jan 20 00:28:25 +0000 2015',
    id: 557333791422046200,
    id_str: '557333791422046209',
    text: 'I wanna love you\neveryday and everynight♪ — ♡ http://t.co/bqM9vzVsZM',
    source: '<a href="http://ask.fm/" rel="nofollow">Ask.fm</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: 
     { id: 2201945882,
       id_str: '2201945882',
       name: '|мαrı juαиα',
       screen_name: 'Rasstih',
       location: 'Guatraché',
       profile_location: null,
       description: '| Bel Kletzel | Lvp & Zg ¡Exijo amor y locura! |мαrı juαиα',
       url: 'https://t.co/JrGrc7xkUL',
       entities: [Object],
       protected: false,
       followers_count: 3917,
       friends_count: 3241,
       listed_count: 0,
       created_at: 'Mon Nov 18 20:36:51 +0000 2013',
       favourites_count: 1207,
       utc_offset: -10800,
       time_zone: 'Buenos Aires',
       geo_enabled: true,
       verified: false,
       statuses_count: 12934,
       lang: 'es',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '131516',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/494774761713451011/4-G4ar0C.png',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/494774761713451011/4-G4ar0C.png',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/556634203635580928/TzJ5rCaO_normal.jpeg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/556634203635580928/TzJ5rCaO_normal.jpeg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/2201945882/1421690987',
       profile_link_color: '7766DD',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'F766CF',
       profile_text_color: '65C286',
       profile_use_background_image: false,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' } ]
